name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Continuous Delivery
    runs-on: ubuntu-20.04
    services:
      zookeeper:
        image: zookeeper:3.7.0
        ports:
          - 2181:2181
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Deploy with Maven
        run: ./mvnw test -B
